name: 'Slacklog action'
description: 'Send a changelog of recent PR to the Slack channel'
author: 'Evgeny Klimenchenko'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  SLACK_CLIENT_ID:
    description: 'Slack client ID to be able to post in the channel'
    required: true
  SLACK_CLIENT_SECRET:
    description: 'Slack client Secret to be able to post in the channel'
    required: true
  GITHUB_TOKEN:
    description: 'Github token to access the pullrequests'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
